################################################################################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CONFIG_MODE SPIx1 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
##### golden image #####;
# golden 1st image should be version 99
#set_property BITSTREAM.CONFIG.NEXT_CONFIG_ADDR 0xF000000 [current_design]
#########################
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.TIMER_CFG 0x100000 [current_design]
################################################################################
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets osys_clk]

# █▀█ █▀█ █ █▀▀
# █▀▄ █▄█ █ █▄▄
set_property PACKAGE_PIN U24  [get_ports {ROIC_DCLK_P[0]}]
set_property PACKAGE_PIN V21  [get_ports {ROIC_DCLK_P[1]}]
set_property PACKAGE_PIN AB21 [get_ports {ROIC_DCLK_P[2]}]

set_property PACKAGE_PIN P19  [get_ports {ROIC_FCLK_P[0]}]
set_property PACKAGE_PIN AD21 [get_ports {ROIC_FCLK_P[1]}]
set_property PACKAGE_PIN AE22 [get_ports {ROIC_FCLK_P[2]}]

set_property PACKAGE_PIN M21  [get_ports {ROIC_DOUT_P[0]}]
set_property PACKAGE_PIN U22  [get_ports {ROIC_DOUT_P[1]}]
set_property PACKAGE_PIN W23  [get_ports {ROIC_DOUT_P[2]}]
set_property PACKAGE_PIN M24  [get_ports {ROIC_DOUT_P[3]}]
set_property PACKAGE_PIN P23  [get_ports {ROIC_DOUT_P[4]}]
set_property PACKAGE_PIN R22  [get_ports {ROIC_DOUT_P[5]}]
set_property PACKAGE_PIN U26  [get_ports {ROIC_DOUT_P[6]}]
set_property PACKAGE_PIN AA23 [get_ports {ROIC_DOUT_P[7]}]
set_property PACKAGE_PIN AB26 [get_ports {ROIC_DOUT_P[8]}]
set_property PACKAGE_PIN AD26 [get_ports {ROIC_DOUT_P[9]}]
set_property PACKAGE_PIN AF24 [get_ports {ROIC_DOUT_P[10]}]
set_property PACKAGE_PIN AE23 [get_ports {ROIC_DOUT_P[11]}]
set_property PACKAGE_PIN W25  [get_ports {ROIC_DOUT_P[12]}]
set_property PACKAGE_PIN Y25  [get_ports {ROIC_DOUT_P[13]}]
set_property PACKAGE_PIN AC23 [get_ports {ROIC_DOUT_P[14]}]
set_property PACKAGE_PIN AD25 [get_ports {ROIC_DOUT_P[15]}]
set_property PACKAGE_PIN AD23 [get_ports {ROIC_DOUT_P[16]}]
# hw roic_reset net namae connect to tp_sel
set_property PACKAGE_PIN R26 [get_ports {F_ROIC_TP_SEL[0]}]
set_property PACKAGE_PIN N26 [get_ports {F_ROIC_SCLK[0]}]
set_property PACKAGE_PIN M25 [get_ports {F_ROIC_SDI[0]}]
set_property PACKAGE_PIN P25 [get_ports {F_ROIC_CS[0]}]
set_property PACKAGE_PIN K26 [get_ports {F_ROIC_SDO[0]}]
set_property PACKAGE_PIN K25 [get_ports {F_ROIC_SDO[1]}]
#set_property PACKAGE_PIN L25 [get_ports {F_ROIC_SDO[2]}]
set_property PACKAGE_PIN R25 [get_ports {F_ROIC_MCLK[0]}]
set_property PACKAGE_PIN T25 [get_ports {F_ROIC_MCLK[1]}]
set_property PACKAGE_PIN P26 [get_ports {F_ROIC_SYNC[0]}]

# █▀▀ ▄▀█ ▀█▀ █▀▀
# █▄█ █▀█ ░█░ ██▄
set_property PACKAGE_PIN E21 [get_ports {GATE_SHIFT_CLK1L}]
set_property PACKAGE_PIN J21 [get_ports {GATE_SHIFT_CLK1R}]
set_property PACKAGE_PIN G21 [get_ports {GATE_SHIFT_CLK2L}]
set_property PACKAGE_PIN C22 [get_ports {GATE_SHIFT_CLK2R}]
set_property PACKAGE_PIN D21 [get_ports {GATE_START_PULSE1[5]}]
set_property PACKAGE_PIN E20 [get_ports {GATE_START_PULSE1[4]}]
set_property PACKAGE_PIN E22 [get_ports {GATE_START_PULSE1[3]}]
set_property PACKAGE_PIN F22 [get_ports {GATE_START_PULSE1[2]}]
set_property PACKAGE_PIN G22 [get_ports {GATE_START_PULSE1[1]}]
set_property PACKAGE_PIN H23 [get_ports {GATE_START_PULSE1[0]}]
set_property PACKAGE_PIN H24 [get_ports {GATE_START_PULSE1[6]}]
set_property PACKAGE_PIN H26 [get_ports {GATE_START_PULSE1[7]}]
set_property PACKAGE_PIN J25 [get_ports {GATE_START_PULSE1[8]}]
set_property PACKAGE_PIN D25 [get_ports {GATE_START_PULSE2[5]}]
set_property PACKAGE_PIN D26 [get_ports {GATE_START_PULSE2[4]}]
set_property PACKAGE_PIN E25 [get_ports {GATE_START_PULSE2[3]}]
set_property PACKAGE_PIN E26 [get_ports {GATE_START_PULSE2[2]}]
set_property PACKAGE_PIN F25 [get_ports {GATE_START_PULSE2[1]}]
set_property PACKAGE_PIN G25 [get_ports {GATE_START_PULSE2[0]}]
set_property PACKAGE_PIN J26 [get_ports {GATE_START_PULSE2[6]}]
set_property PACKAGE_PIN J24 [get_ports {GATE_START_PULSE2[7]}]
set_property PACKAGE_PIN L22 [get_ports {GATE_START_PULSE2[8]}]
set_property PACKAGE_PIN B26 [get_ports {GATE_OUT_EN1L}]
set_property PACKAGE_PIN J20 [get_ports {GATE_OUT_EN1R}]
set_property PACKAGE_PIN C24 [get_ports {GATE_OUT_EN2L}]
set_property PACKAGE_PIN K23 [get_ports {GATE_OUT_EN2R}]
set_property PACKAGE_PIN C26 [get_ports {GATE_ALL_OUT}]
set_property PACKAGE_PIN E23 [get_ports {GATE_ALL_OUT_R}]
# G26:F_INDL/R  # H22:F_FB # K20:F_UD
set_property PACKAGE_PIN G26 [get_ports {GATE_CONFIG[0]}]
set_property PACKAGE_PIN H22 [get_ports {GATE_CONFIG[1]}]
set_property PACKAGE_PIN K20 [get_ports {GATE_CONFIG[2]}]
set_property PACKAGE_PIN D19 [get_ports {GATE_VGH_RST}]
set_property PACKAGE_PIN D20 [get_ports {F_NBIAS_CTRL}]
# set_property PACKAGE_PIN C21 [get_ports {FLASH_RESET}]
# set_property PACKAGE_PIN A23 [get_ports {TP}]
# set_property PACKAGE_PIN A24 [get_ports {TP}]

# █▀▀ ▀█▀ █▀▀
# ██▄ ░█░ █▄▄
set_property PACKAGE_PIN AB11 [get_ports SYSTEM_CLK_P]
set_property PACKAGE_PIN B24 [get_ports {FLASH_D[0]}]
set_property PACKAGE_PIN A25 [get_ports {FLASH_D[1]}]
set_property PACKAGE_PIN B22 [get_ports {FLASH_D[2]}]
set_property PACKAGE_PIN A22 [get_ports {FLASH_D[3]}]
set_property PACKAGE_PIN C23 [get_ports FLASH_FCS]
# set_property PACKAGE_PIN C26 [get_ports FLASH_RESET]
set_property PACKAGE_PIN B16 [get_ports EEPROM_SCL]
set_property PACKAGE_PIN C16 [get_ports EEPROM_SDA]
set_property PACKAGE_PIN D24 [get_ports TEMP_SCL]
set_property PACKAGE_PIN D23 [get_ports TEMP_SDA]
set_property PACKAGE_PIN B20 [get_ports UART_TX]
set_property PACKAGE_PIN A20 [get_ports UART_RX]
set_property PACKAGE_PIN A17 [get_ports EXT_IN]
set_property PACKAGE_PIN B19 [get_ports EXT_OUT]
set_property PACKAGE_PIN A18 [get_ports EXP_IN]
set_property PACKAGE_PIN B17 [get_ports {STATUS_LED[0]}]
set_property PACKAGE_PIN A19 [get_ports {STATUS_LED[1]}]
set_property PACKAGE_PIN H9  [get_ports {PWR_EN[0]}]
set_property PACKAGE_PIN J23 [get_ports {PWR_EN[1]}]
set_property PACKAGE_PIN G24 [get_ports {PWR_EN[2]}]
set_property PACKAGE_PIN F23 [get_ports {PWR_EN[3]}]
set_property PACKAGE_PIN F24 [get_ports {PWR_EN[4]}]
# phy
set_property PACKAGE_PIN D8  [get_ports PHY_RESET_N]
set_property PACKAGE_PIN F10 [get_ports PHY_MDC]
set_property PACKAGE_PIN D9  [get_ports PHY_MDIO]
set_property PACKAGE_PIN P2  [get_ports {PHY_SIP[0]}]
set_property PACKAGE_PIN M2  [get_ports {PHY_SIP[1]}]
set_property PACKAGE_PIN H6  [get_ports PHY_CLK_P]
#tb_pin
set_property PACKAGE_PIN AE17 [get_ports tb_alignreq]
set_property PACKAGE_PIN AF17 [get_ports tb_aligndone]
# phy
set_property PACKAGE_PIN D8  [get_ports PHY_RESET_N]
set_property PACKAGE_PIN F10 [get_ports PHY_MDC]
set_property PACKAGE_PIN D9  [get_ports PHY_MDIO]
set_property PACKAGE_PIN P2  [get_ports {PHY_SIP[0]}]
set_property PACKAGE_PIN M2  [get_ports {PHY_SIP[1]}]
set_property PACKAGE_PIN H6  [get_ports PHY_CLK_P]
#tb_pin
set_property PACKAGE_PIN AE17 [get_ports tb_alignreq]
set_property PACKAGE_PIN AF17 [get_ports tb_aligndone]

# █ █▀█
# █ █▄█
##############################
##### Unused output port #####
set_property IO_BUFFER_TYPE NONE [get_ports GATE_SHIFT_CLK]
set_property IO_BUFFER_TYPE NONE [get_ports GATE_OUT_EN1  ]
set_property IO_BUFFER_TYPE NONE [get_ports GATE_OUT_EN2  ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_ALL_OUT_R      ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_OUT_EN1L       ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_OUT_EN1R       ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_OUT_EN2L       ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_OUT_EN2R       ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_SHIFT_CLK1L    ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_SHIFT_CLK1R    ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_SHIFT_CLK2L    ]
## set_property IO_BUFFER_TYPE NONE [get_ports GATE_SHIFT_CLK2R    ]
## set_property IO_BUFFER_TYPE NONE [get_ports {GATE_START_PULSE2[0]}]
## set_property IO_BUFFER_TYPE NONE [get_ports PWR_EN[5]           ]
# set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
# set_property BITSTREAM.General.UnconstrainedPins {Allow} [current_design]
##########################
set_property IOSTANDARD DIFF_SSTL135 [get_ports SYSTEM_CLK_P]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_CS[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_MCLK[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_MCLK[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_TP_SEL[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_SCLK[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_SDI[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_SDO[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_SDO[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {F_ROIC_SYNC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports FLASH_FCS]
set_property IOSTANDARD LVCMOS33 [get_ports GATE_ALL_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports GATE_ALL_OUT_R]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_CONFIG[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_CONFIG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_CONFIG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports GATE_OUT_EN1]
set_property IOSTANDARD LVCMOS33 [get_ports GATE_OUT_EN2]
# set_property IOSTANDARD LVCMOS33 [get_ports GATE_SHIFT_CLK]
# set_property IOSTANDARD LVCMOS18 [get_ports {GATE_START_PULSE2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_START_PULSE1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports GATE_VGH_RST]
set_property IOSTANDARD LVCMOS33 [get_ports F_NBIAS_CTRL]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports TEMP_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports TEMP_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports EEPROM_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_IN]
set_property IOSTANDARD LVCMOS33 [get_ports EXT_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS_LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS_LED[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_MDC]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_MDIO]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RESET_N]
set_property IOSTANDARD LVCMOS25 [get_ports {PWR_EN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports tb_aligndone]
set_property IOSTANDARD LVCMOS18 [get_ports tb_alignreq]

set_property IOSTANDARD LVCMOS33 [get_ports EXP_IN]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_OUT_EN1L}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_OUT_EN1R}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_OUT_EN2L}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_OUT_EN2R}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_SHIFT_CLK1L}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_SHIFT_CLK1R}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_SHIFT_CLK2L}]
set_property IOSTANDARD LVCMOS33 [get_ports {GATE_SHIFT_CLK2R}]
# ▀█▀ █ █▀▄▀█ █▀▀
# ░█░ █ █░▀░█ ██▄
create_clock -period 5.000 [get_ports SYSTEM_CLK_P]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets TP_1_OBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sroic_dclk_0]
set_input_delay -clock [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -clock_fall -min -add_delay 0.0 [get_ports {ROIC_DOUT_N[*]}]
set_input_delay -clock [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -clock_fall -max -add_delay 0.4 [get_ports {ROIC_DOUT_N[*]}]
set_input_delay -clock [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -min -add_delay 0.0 [get_ports {ROIC_DOUT_N[*]}]
set_input_delay -clock [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -max -add_delay 0.4 [get_ports {ROIC_DOUT_N[*]}]
set_input_delay -clock [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -clock_fall -min -add_delay 0.0 [get_ports {ROIC_DOUT_P[*]}]
set_input_delay -clock [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -clock_fall -max -add_delay 0.4 [get_ports {ROIC_DOUT_P[*]}]
set_input_delay -clock [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -min -add_delay 0.0 [get_ports {ROIC_DOUT_P[*]}]
set_input_delay -clock [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -max -add_delay 0.4 [get_ports {ROIC_DOUT_P[*]}]
# RXAUI bridge asynchronous paths
set_max_delay -to [get_pins SYNTH.RXAUI_INST/U0/rxaui_block_i/rxaui_cl_resets_i/reset156_r1_reg/S] 6.400
set_max_delay -to [get_pins SYNTH.RXAUI_INST/U0/rxaui_block_i/rxaui_cl_resets_i/reset156_r2_reg/S] 6.400
set_max_delay -to [get_pins SYNTH.RXAUI_INST/U0/rxaui_block_i/rxaui_cl_resets_i/reset156_r3_reg/S] 6.400
set_property ASYNC_REG true [get_cells SYNTH.RXAUI_INST/U0/rxaui_block_i/rxaui_cl_resets_i/reset156_r1_reg]
set_property ASYNC_REG true [get_cells SYNTH.RXAUI_INST/U0/rxaui_block_i/rxaui_cl_resets_i/reset156_r2_reg]
set_property ASYNC_REG true [get_cells SYNTH.RXAUI_INST/U0/rxaui_block_i/rxaui_cl_resets_i/reset156_r3_reg]
# ASYNC Signal
set_false_path -from [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/DDR_RSTN_GEN/srstn_reg/C]
set_false_path -from [get_clocks clk_out1_PLL_20M_100M_200M_250M] -to [get_clocks clk_out2_PLL_20M_100M_200M_250M]
set_false_path -from [get_clocks clk_out1_PLL_20M_100M_200M_250M] -to [get_clocks clk_out1_PLL_240M]
set_false_path -from [get_clocks clk_out1_PLL_20M_100M_200M_250M] -to [get_clocks clk_pll_i]
set_false_path -from [get_clocks clk_out2_PLL_20M_100M_200M_250M] -to [get_clocks clk_out1_PLL_20M_100M_200M_250M]
set_false_path -from [get_clocks clk_out2_PLL_20M_100M_200M_250M] -to [get_clocks clk_out1_PLL_240M]
set_false_path -from [get_clocks clk_out2_PLL_20M_100M_200M_250M] -to [get_clocks clk_pll_i]
set_false_path -from [get_clocks clk_out4_PLL_20M_100M_200M_250M] -to [get_clocks clk_pll_i]
set_false_path -from [get_clocks clk_out1_PLL_240M]               -to [get_clocks clk_out2_PLL_20M_100M_200M_250M]
set_false_path -from [get_clocks clk_out1_PLL_240M]               -to [get_clocks clk_pll_i]
set_false_path -from [get_clocks clk_pll_i]                       -to [get_clocks clk_out1_PLL_20M_100M_200M_250M]
set_false_path -from [get_clocks clk_pll_i]                       -to [get_clocks clk_out2_PLL_20M_100M_200M_250M]
set_false_path -from [get_clocks clk_pll_i]                       -to [get_clocks clk_out1_PLL_240M]
set_false_path -from [get_clocks SYNTH.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK] -to [get_clocks clk_out2_PLL_20M_100M_200M_250M]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_clock_groups -asynchronous -group [get_clocks SYNTH.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]]
set_clock_groups -asynchronous -group [get_clocks SYNTH.G_rxaui_2p5G.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_clock_groups -asynchronous -group [get_clocks SYNTH.G_rxaui_2p5G.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK] -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKOUT0]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]] -group [get_clocks SYNTH.G_rxaui_2p5G.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]] -group [get_clocks SYNTH.G_rxaui_10G.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -group [get_clocks SYNTH.G_rxaui_10G.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK]

# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/ROIC_CLK_GEN/inst/plle2_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]] -group [get_clocks SYNTH.G_rxaui_2p5G.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK]
# set_clock_groups -asynchronous -group [get_clocks SYNTH.G_rxaui_2p5G.RXAUI_INST/U0/rxaui_block_i/gt0_wrapper_i/gtxe2_i/TXOUTCLK] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]

# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/mig_7series_0/u_cpu_mig_7series_0_1_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT0]] -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]]
# set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins SYNTH.GEN_CPU_14.CPU_INST/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]]

#v2
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins GEV_CPU/cpu_i/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]] 
                               -group [get_clocks -of_objects [get_pins GEV_CPU/cpu_i/sdram_0/u_cpu_sdram_0_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins GEV_CPU/cpu_i/sdram_0/u_cpu_sdram_0_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] 
                               -group [get_clocks -of_objects [get_pins GEV_CPU/cpu_i/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT0]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U0_TI_TFT_TOP/U0_TI_CLOCK_MANAGER/CLK_GEN/inst/plle2_adv_inst/CLKOUT1]] 
                               -group [get_clocks -of_objects [get_pins GEV_CPU/cpu_i/clk_wiz_0/inst/CLK_CORE_DRP_I/clk_inst/mmcm_adv_inst/CLKOUT1]]